firmware=cc
alink=0
mcs_index=1
link_id=7669206
fec_n=12
unit=drone
guard_interval=long
wlan=wlan0
ldpc=0
udp_port=5600
video_height=1080
driver_txpower_override=1
txpower=1
pool_timeout=0
fec_k=8
region=00
sound=0
stream=0
stbc=0
rcv_buf=456000
buf_level=1
alignment=0
dec_mode=1
video_width=1920
channel=64
lang=cn
ground_res=1080p120hz
frequency=
sound_volume=30
frame_type=data
bad_frame=176
bandwidth=20
hdmi_attr=rgb
